#!/bin/bash
# List of environment variables and module loads for tuning tasks

export TUNING_CUDA_VERSION_MAJOR=12
export TUNING_CUDA_VERSION_MINOR=1
export TUNING_CUDA_VERSION_PATCH=1

export TUNING_CUDA_VERSION=${TUNING_CUDA_VERSION_MAJOR}.${TUNING_CUDA_VERSION_MINOR}
export TUNING_CUDA_VERSION_SHORT=${TUNING_CUDA_VERSION_MAJOR}${TUNING_CUDA_VERSION_MINOR}
export TUNING_CUDNN_VERSION=9.5
export TUNING_CUDNN_VERSION_WITH_PATCH=9.5.1
export TUNING_HPCX_VERSION=2.20
export TUNING_NCCL_VERSION=2.23
export TUNING_NCCL_VERSION_WITH_PATCH=2.23.4-1

export TUNING_PYTHON_VERSION=3.10.14
export TUNING_TORCH_VERSION=2.4.0
export TUNING_TORCHVISION_VERSION=0.19.0
export TUNING_NEMO_COMMIT=0504c927afe61ddd40ade18f8553d0f52a65f509
export TUNING_APEX_COMMIT=b7a4acc1
export TUNING_FLASH_ATTENTION_VERSION=2.4.2
export TUNING_TRANSFORMER_ENGINE_COMMIT=c81733f1032a56a817b594c8971a738108ded7d0

source /etc/profile.d/modules.sh
module load cuda/${TUNING_CUDA_VERSION}/${TUNING_CUDA_VERSION}.${TUNING_CUDA_VERSION_PATCH}
module load cudnn/${TUNING_CUDNN_VERSION}/${TUNING_CUDNN_VERSION_WITH_PATCH}
module load hpcx/${TUNING_HPCX_VERSION}
module load nccl/${TUNING_NCCL_VERSION}/${TUNING_NCCL_VERSION_WITH_PATCH}

export LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH
